name: Macos

on: [push]

jobs:           
    macos-latest:
        runs-on: macos-13 # https://github.com/actions/runner-images
        permissions:
          id-token: write
          contents: read
          checks: write
        steps:
          - uses: actions/checkout@v3
          - name: Setup .NET Core SDK 3
            uses: actions/setup-dotnet@v2
            with:	
                dotnet-version: 3.1.x
          - name: Setup .NET Core SDK 6
            uses: actions/setup-dotnet@v2
            with:	
                dotnet-version: 6.0.x
          - name: Setup .NET Core SDK 7
            uses: actions/setup-dotnet@v2
            with:	
                dotnet-version: 7.0.x            
          - name: Setup .NET Core SDK 8
            uses: actions/setup-dotnet@v2
            with:	
                dotnet-version: 8.0.x
          - name: Setup .NET Core SDK 9
            uses: actions/setup-dotnet@v2
            with:	
                dotnet-version: 9.0.x
          - name: Install dependencies
            run: dotnet restore
          - name: Build
            run: dotnet build --configuration Release --no-restore
          - name: Test
            run: dotnet test --configuration Release --logger:"trx" --no-restore
          - name: Test Report
            if: success() || failure()
            uses: dorny/test-reporter@v1
            with:
                name: Xunit Tests
                path: "test/Avalonia.I18N.Test/TestResults/*.trx"                            
                reporter: dotnet-trx
                fail-on-error: true
